
<?php require_once "../stdSscript/stdPHPobjGen.php"; ?>
<!-- stdPHPobjGen is std script to generate HTML

class AB_objGen
For now only two type of inputs are generated

1 - Yes/No or True/False
setYesNoField
2 - Lister of foreign table data
setListerField

-->


<div class="ab-colors ab-spaceless"  ng-model="vgb_cntr"  >
	
	<?php require_once "../stdCscript/stdDbButtons.php"; ?>

<!-- stdDbButtons contain all update buttons (New - Upd - Del - Share) and has a back button
The display is initialized by ABclearUpdButtons  and ABinitTbl  - displays back button only
The display of proper update buttons is maintained by ABchk() automaticly
All update button call the standard function ABupd() 
-->	
	
</div>

<div class="ab-spaceless" ng-init="ABShowButtonPad('hide')">

<textarea class="hidden" ab-updSuccess="" >

var id=$scope.idVGB_CNTR;
if (data['posts'].requestMethod == 'DELETE')
{
	id = 0;
}
$scope.ABinitTbl('vgb_cntr','VGB_CNTR_CNTID');
$scope.ABlstAlias('VGB_CNTR_CNTID','VGB_CNTR_CNTID','vgb_cntr','lister');
$scope.ABupdChkObj('idVGB_CNTR',id,true);
$scope.ABupdChkObj('VGB_CNTR_CNTID','',false);
$scope.ABchk();

</textarea>
<!--
Attribute ab-updSuccess - Optional
If present and ABupd is successfull
ABupd() will execute (eval) the value of the object

Note that $scope needs to be in the code as opposed to data-ng-init= above
-->
</div>
<div class="row mygrid-wrapper-div" 
data-ng-init="
ABinitTbl('vgb_cntr','idVGB_CNTR');
ABchk();
ABlstAlias('idVGB_CNTR','idVGB_CNTR','vgb_cntr','lister');
idVGB_CURR=0;
ABlst('idVGB_CURR','idVGB_CURR','vgb_curr',0);
" >
<!--
Angular data-ng-init - Optional but needed
If present will execute the $scope functions

-->




	<form id="mainForm" name="mainForm"  ab-view="vgb_cntr" ab-main="vgb_cntr"  >
<!--
ab-main="vgb_cntr" mandatory
Instructs update process main table to update
-->


		<div class="col-sm-6">

			<table class="table table-striped">
				<tr class="ab-border" >
					<td>
				 		<a ng-click="ABShowButtonPad('');ABupdChkObj('idVGB_CNTR','0',true);ABupdChkObj('VGB_CNTR_CNTID','',false);ABchk();" >
 				 		
							<span >New</span>
							<span  class="glyphicon glyphicon-pencil" ></span>
							
						</a>
						
						
						&nbsp;&nbsp;							
						<label ab-label="VGB_CNTR_CNTID">
						</label>
					</td>	
					<td><label ab-label="VGB_CNTR_DESCR" ng-click="abButtonPad='';">
					</label></td>	
					<td><label ab-label="STD_CURRENCY">
					</label></td>	
				</tr>	
				<tr ng-repeat="xx in lister" class="{{xx.idVGB_CNTR!=idVGB_CNTR?'':'ab-active'}}">
					<td>
						
 				 		<a ng-click="ABShowButtonPad('');ABupdChkObj('idVGB_CNTR',xx.idVGB_CNTR,true);ABupdChkObj('VGB_CNTR_CNTID','',false);ABchk();" >
 				 		
							<span >Edit</span>
							<span  class="glyphicon glyphicon-pencil" ></span>
							
						</a>
						&nbsp;&nbsp;				
						{{xx.VGB_CNTR_CNTID}}
					</td>	
					<td>
						{{xx.VGB_CNTR_DESCR}}
					</td>	
					<td>
					<span ng-repeat="y in vgb_curr" class="{{y.idVGB_CURR==xx.VGB_CNTR_CURID?'':'hidden'}}">
						{{y.VGB_CURR_DESCR}}
					<span>	
					</td>
				</tr>
			</table>				

		</div>

		<div class="col-sm-6">
		
			<div style="position:fixed;padding:20px;" >
			<table class="table ab-border {{abButtonPad!='hide'?'':'hidden'}}" >
			
				<tr>
					<td colspan=2 class="ab-colors">
					</td>
				</tr>

				<tr>
					<td style="width:40%;">
						<label class="btn-md"  ab-label="VGB_CNTR_CNTID">Ctnr</label>
					</td>
					
					<td style="width:60%;">
						<input  class="hidden" ab-btrigger="vgb_cntr" ng-model="idVGB_CNTR" />
						<Input 	size=5 ng-model="VGB_CNTR_CNTID" value="" />
									
					</td>
				</tr>
				<tr>
					<td>
						<label class="btn-md"  ab-label="VGB_CNTR_DESCR">desc</label>
					</td>
					
					<td>
						<Input 	size=10 ng-model="VGB_CNTR_DESCR" value="" />
									
					</td>
				</tr>

			<tr>
			<td>
				<label class="btn-md"   ab-label="VGB_CUST_CURID">VGB_CUST_CURID</label>
			</td>
			<td>

<?php
$keepOrg = 1; 
$repeatIn = "vgb_curr";
$searchIn = "";
$refName = "vgb_curr"; // unique
$refModel = "VGB_CNTR_CURID"; // unique
$repeatInRef = "idVGB_CURR"; //Unique
$searchRefDesc = "";// implode("&nbsp;&nbsp;",array("{{VGB_CURR_CURID}}","{{VGB_CURR_DESCR}}"));
$refDesc = implode("&nbsp;&nbsp;",array("{{ab_rloop.VGB_CURR_CURID}}","{{ab_rloop.VGB_CURR_DESCR}}"));
$refDetail = "";
$refDetailLink = "";
$ignTrig = 'ng-click="' . "hold=VGB_CURR_CURID;VGB_CURR_CURID='';VGB_CURR_CURID_F='';ABlst('VGB_CURR_CURID','VGB_CURR_CURID','vgb_curr',0);VGB_CURR_CURID=hold;".'"';

$tmp = new AB_objGen;
$tmp->setListerField($keepOrg,$repeatIn,$searchIn,$refName,$refModel,$searchInRef,$searchRefDesc,$repeatInRef,$refDesc,$refDetail,$refDetailLink,$ignTrig);
?>

<script>

/*


The script below was generated by AB_objGen CLASS - setListerField function with the parameters above


<!-- onclick="$('#VGB_CNTR_CURIDmain').html($('#VGB_CNTR_CURIDval').html());" -->

				<div class="text-muted "  ng-click="hold=VGB_CURR_CURID;VGB_CURR_CURID='';VGB_CURR_CURID_F='';ABlst('VGB_CURR_CURID','VGB_CURR_CURID','vgb_curr',0);VGB_CURR_CURID=hold;" ab-objLister="ab-lister-vgb_curr,1"  >
					<span class="ab-border"  >
						<input id="VGB_CNTR_CURID" ng-model="VGB_CNTR_CURID"  size=5 />
						<span id="VGB_CNTR_CURIDmain" >
						
						

	<span  ng-repeat="ab_rloop in vgb_curr"  > 

		<span class="text-muted {{ab_rloop.idVGB_CURR!=VGB_CNTR_CURID?'hidden':''}}">
		{{ab_rloop.VGB_CURR_CURID}}&nbsp;&nbsp;{{ab_rloop.VGB_CURR_DESCR}} 	
		</span>
	</span>

							
						</span>
						<span class="caret"></span>
					</span>
					
								
	
				</div>
				<div class="hidden ab-fixed" ab-flst="ab-lister-vgb_curr" >
					
					<div class="mygrid-wrapper-divSm" >
					<table class=" table-bordered" >
					<tr ng-repeat="ab_rloop in vgb_curr" >
					<td>
						<span id='vgb_curr{{$index}}' >
							<input type="hidden"  name="VGB_CNTR_CURID" value="{{ab_rloop.idVGB_CURR}}" />
							
							
						</span>
						<div class="btn btn-xs {{ab_rloop.idVGB_CURR!=VGB_CNTR_CURID?'hidden':''}}" >

							<span class="ab-border">
								
								&radic; 
								
							</span>
							&nbsp;
							
							<label>
							{{ab_rloop.VGB_CURR_CURID}}&nbsp;&nbsp;{{ab_rloop.VGB_CURR_DESCR}}
							</label>
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							
						</div>

									
						
						
						<div class="btn btn-xs {{ab_rloop.idVGB_CURR!=VGB_CNTR_CURID?'':'hidden'}}"
							value='vgb_curr{{$index}}'
							dflval="{{ab_rloop.idVGB_CURR}}"
							onclick="deflectVal($(this).attr('dflval'),'VGB_CNTR_CURID');" 
						>	

							<span class="ab-border" style="color:transparent;">
								&radic; 
							</span>
							&nbsp;
							<span >
							<label>
							{{ab_rloop.VGB_CURR_CURID}}&nbsp;&nbsp;{{ab_rloop.VGB_CURR_DESCR}}
							</label>
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							</span>
						</div>
						
						
						
						<div ab-fxVGB_CNTR_CURIDde class='btn-xs disabled hidden' style="padding-left:20px;" >
							<div class="well well-sm">
							<strong>
							
							</strong>
							</div>
							
					      	</div>
						
					</td>
					</tr>
					
					</table>
					</div>
				</div>

*/
</script>


				</td>
				</tr>
			</table>
			</div>
		</div>
	</form>
</div>	
